// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/recommendations": {
            "post": {
                "description": "Runs the recommendation pipeline and returns ranked candidates for a vacancy.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recommendations"
                ],
                "summary": "Create candidate recommendations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional correlation ID",
                        "name": "X-Request-Id",
                        "in": "header"
                    },
                    {
                        "description": "Recommendation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RecommendationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RecommendationResponse"
                        },
                        "headers": {
                            "X-Request-Id": {
                                "type": "string",
                                "description": "Correlation ID"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-Id": {
                                "type": "string",
                                "description": "Correlation ID"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-Id": {
                                "type": "string",
                                "description": "Correlation ID"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "headers": {
                            "X-Request-Id": {
                                "type": "string",
                                "description": "Correlation ID"
                            }
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns Prometheus exposition metrics.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "Prometheus metrics",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "X-Request-Id": {
                                "type": "string",
                                "description": "Correlation ID"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "model.FinalCandidate": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "type": "string"
                },
                "final_score": {
                    "type": "number"
                }
            }
        },
        "model.RecommendationRequest": {
            "type": "object",
            "properties": {
                "top_k": {
                    "type": "integer"
                },
                "top_n": {
                    "type": "integer"
                },
                "vacancy_text": {
                    "type": "string"
                }
            }
        },
        "model.RecommendationResponse": {
            "type": "object",
            "properties": {
                "top_candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.FinalCandidate"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Talentmine Backend API",
	Description:      "Go orchestrator API for vacancy-based candidate recommendations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
